### ISSUE TITLE
Translate CHANGELOG.md

### ISSUE THREAD

**Issue by ttres** [puppet-br/pcp#10]
What: we should translate the project's CHANGELOG to English.

Why: this is necessary so foreign people can know the evolution and contribute to our project.

When it will be done: when the CHANGELOG file could be read by a foreign contributor.

**Comment by ttres** [comment]
The CHANGELOG.md file is already in English, so no action is required.

**Comment by mtulio** [comment]
Wrong issue reference on last PR. Please ignore it!
