### ISSUE TITLE
Avaliar uso do Debian 8 como box básico

### ISSUE THREAD

**Issue by ttres** [puppet-br/pcp#11]
O quê: avaliar se é possível utilizar uma imagem do Debian 8 como base para a montagem da infraestrutura do projeto.

Porquê: permitir que o Debian 8 seja um sistema operacional válido para a criação da infraestrutura do projeto, considerando que muitas empresas/sysadmins utilizam o mesmo.

Quando estará pronto: quando o uso de uma imagem do Debian 8 puder ser utilizada como base da infraestrutura do projeto, ou se chegar à conclusão de que isto não é tecnicamente viável.

**Comment by gutocarvalho** [comment]
Excelente, provavelmente teremos que enviar PRs para o módulo instruct/puppet pois é ele que faz a instalação do puppetserver, no caso do debian8 teremos que mexer nele.

https://bitbucket.org/instruct/puppet-puppet

**Comment by gutocarvalho** [comment]
For now we'll support only EL7.
