### ISSUE TITLE
Planejamento de PCP em docker

### ISSUE THREAD

**Issue by ttres** [puppet-br/pcp#14]
*O quê*: planejar a implementação de uma infraestrutura PCP utilizando contêineres Docker.

*Porquê*: permitir que as funcionalidades do projeto estejam disponíveis para usuários de contêineres Docker, evitando o uso de máquinas virtuais.

*Quando estará pronto*: quando as mesmas ferramentas disponibilizadas pelo projeto possam ser inicializadas utilizando a tecnologia de contêineres, sem o uso de máquinas virtuais.

**Comment by gutocarvalho** [comment]
Excelente, adiciono que vamos usar docker via vagrant ;)

**Comment by jairojunior** [comment]
+1

Já fiz uma brincadeira com o Docker de provider e Puppet de provisioner no Vagrant. Meu ponto de partida foi este projeto aqui: https://github.com/BashtonLtd/docker-vagrant-images/tree/master/centos7/puppet4

**Comment by gutocarvalho** [comment]
At the moment we don't have intentions to create a docker version of PCP.

**Comment by ttres** [comment]
Just to keep the reference here, CampToCamp guys are working in a Puppet environment using Docker images and Rancher as the orchestration manager. The details [are here](http://www.camptocamp.com/en/actualite/an-orchestrated-puppet-infrastucture-with-docker-and-rancher/).

**Comment by jairojunior** [comment]
@ttres Interesting, but they're using Docker provision capabilities to build images: e.g.https://hub.docker.com/r/camptocamp/puppetserver/~/dockerfile/

It's seems overcomplicated. A Puppet module seems more suitable to manage Puppet Server.

Another alternative would be to break this image into a more simple core image and others images built from this core with additional features (log appenders and etc)
