### ISSUE TITLE
Suporte box Vagrant da puppetlabs (e.g. puppetlabs/centos-7.0-64-puppet)

### ISSUE THREAD

**Issue by jairojunior** [puppet-br/pcp#15]
Reutilizar boxes populares reduz o esforço de manutenção, economiza recursos para quem trabalha com Vagrant com frequência e de bônus ainda suporta outros providers, o que é uma boa para quem tem licença do VMWare Fusion ou Workstation.

Fui capaz de fazer funcionar com a referida box apenas incluindo `yum install git -y` no instala.sh e desabilitando o firewalld (futuramente podemos atualizar os roles/profiles).

**Comment by jairojunior** [comment]
Abri um issue no pcp-controlrepo também: https://github.com/gutocarvalho/pcp-controlrepo/issues/6

**Comment by gutocarvalho** [comment]
Vamos verificar essa dependencia do GIT em outras boxes, mas no momento vamos manter a box gutocarvalho/centos7x64

**Comment by gutocarvalho** [comment]
Done!
