### ISSUE TITLE
Mover instruções de setup para script setup.sh

### ISSUE THREAD

**Issue by jairojunior** [puppet-br/pcp#16]
Reduz o tempo de onboarding de novatos no projeto. Documentação executável é sempre melhor. =)

**Comment by gutocarvalho** [comment]
Ainda não chegamos a um consenso quanto a essa mudança, acreditamos que ler o README é essencial em qualquer projeto, mesmo que seja para executar um script.

Vamos manter a issue aberta para amadurecer o assunto.

**Comment by gutocarvalho** [comment]
We'll consider your suggestion in the future, thanks.
