### ISSUE TITLE
Considerar utilizar shared folder para environment/hiera

### ISSUE THREAD

**Issue by jairojunior** [puppet-br/pcp#17]
O modelo atual com instalação do r10k no PM e configuração do r10k.yaml é interessante para exemplificar como as coisas funcionam na "vida real", mas deixa o ciclo de desenvolvimento lento. Por exemplo, caso deseje modificar algum role/profile será necessário fazer um PR para o pcp-controlrepo para só então testar meu ambiente.

No meu fluxo de desenvolvimento atual com o Vagrant tenho um Puppetfile dentro do projeto Vagrant, e um `r10k puppetfile install` no meu setup.sh, com isso, quando abro meu projeto Vagrant no meu editor de texto tenho visibilidade de todo o código Puppet e/ou do Hiera disponível no environment e posso facilmente testar mudanças/evoluções do código.

Enfim, a ideia é discutir o trade-off entre rapidez de feedback/velocidade de desenvolvimento X semelhança com ambiente real.

**Comment by gutocarvalho** [comment]
Você deve fazer um fork do repositório controlrepo e usar seu próprio controlrepo.

Basta alterar a variavel CONTROL no install.sh e apontar para o seu repositorio pessoal.

O repo pcp-controlrepo é um exemplo, apenas isto.
