### ISSUE TITLE
Update Puppet Server version

### ISSUE THREAD

**Issue by ttres** [puppet-br/pcp#18]
*What*: update the Puppet Server version, from 2.1.2 to 2.3.1.

*Why*: the new version available allows the execution of full featured services and avoid know bugs.

*Done*: when the Puppet Server delivers the new features and the version string shows 2.3.1.

EDIT: update the Puppet Server version.

**Comment by gutocarvalho** [comment]
Puppet Server 2.3.1 works very nice.

If anybody want's to check just get the branch meetup of pcp-controlrepo.

**Comment by gutocarvalho** [comment]
We'll wait until Puppet Explorer gets PuppetDB 4 support, then we should merge with pcp-controlrepo production branch

**Comment by gutocarvalho** [comment]
Done!
