### ISSUE TITLE
Update PuppetDB version

### ISSUE THREAD

**Issue by ttres** [puppet-br/pcp#20]
*What*: update the PuppetDB version to 4.0.0, and test it with the Puppet Explorer console.

*Why*: the new version available allows the execution of full featured services and avoid know bugs.

*Done*: when the PuppetDB delivers the new features and the version string shows 4.0.0.

**Comment by ttres** [comment]
The Puppet Explorer stop working when the PuppetDB version is updated to 4.0.0, because of this [bug](https://github.com/spotify/puppetexplorer/issues/49).

Because of this, the issue will remain open.

**Comment by gutocarvalho** [comment]
Puppet Server 2.3.1 works very nice with PuppetDB 4.0.0.

If anybody want's to check just get the branch meetup of pcp-controlrepo.

**Comment by gutocarvalho** [comment]
Done!
