### ISSUE TITLE
Update ActiveMQ version

### ISSUE THREAD

**Issue by ttres** [puppet-br/pcp#21]
*What*: update the ActiveMQ version to 5.11, using the external package.

*Why*: the new version available allows the execution of full featured services and avoid know bugs.

*Done*: when the ActiveMQ delivers the new features and the version string shows 4.11.

**Comment by ttres** [comment]
The package is available from [this external repo](http://copr-be.cloud.fedoraproject.org/results/lkiesow/apache-activemq-dist/epel-7-x86_64/activemq-dist-5.11.1-3.el7.centos/).

**Comment by gutocarvalho** [comment]
Done!
